metadata:
  name: test-openbao
spec:
  namespace: openbao-test
  create_namespace: true
  server_container:
    replicas: 1
    data_storage_size: "5Gi"
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
  ui_enabled: true
  ingress:
    enabled: true
    hostname: test-openbao.example.com
