apiVersion: kubernetes.project-planton.org/v1
kind: KubernetesKeycloak
metadata:
  name: test-keycloak
  labels:
    environment: test
spec:
  target_cluster:
    cluster_name: "test-gke-cluster"
  namespace:
    value: "keycloak-test"
  create_namespace: true
  container:
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  ingress:
    enabled: false
    hostname: ""

