apiVersion: kubernetes.project-planton.org/v1
kind: KubernetesNamespace
metadata:
  name: test-namespace
spec:
  name: test-namespace
  labels:
    team: platform-engineering
    environment: test
    cost-center: engineering
    created-by: project-planton
  annotations:
    description: "Test namespace created by Project Planton"
  resource_profile:
    preset: BUILT_IN_PROFILE_SMALL
  network_config:
    isolate_ingress: true
    restrict_egress: true
    allowed_ingress_namespaces:
      - "kube-system"
      - "istio-system"
    allowed_egress_cidrs:
      - "10.0.0.0/8"
  pod_security_standard: POD_SECURITY_STANDARD_BASELINE
